Set ansible_python_interpreter
epfl-si/search-inside pull request #9
Opened 2022-08-18 09:11 UTC by williambelle

2022-08-18 12:48 UTC, williambelle commented
See https://github.com/epfl-si/ansible.suitcase/blob/master/COOKBOOK.md#using-the-suitcases-python-for-your-local-tasks

2022-08-18 16:31 UTC, domq requested changes
Sorry to be that guy, but...

2022-08-18 16:31 UTC, domq commented on ansible/elasticsible
> +ansible_args=(-e "elasticsible_dir=$PWD/ansible-tmp")
`elasticsible_dir` → `elasticsible_suitcase_dir`?

2022-08-18 16:31 UTC, domq commented on ansible/host-prod
> +wwp      ansible_connection=local  ansible_python_interpreter={{elasticsible_dir}}/bin/python3  openshift_namespace=wwp
Same

2022-08-18 16:31 UTC, domq commented on ansible/host-test
> +wwp-test      ansible_connection=local  ansible_python_interpreter={{elasticsible_dir}}/bin/python3  openshift_namespace=wwp-test
Same

2022-08-19 07:45 UTC, domq approved these changes

2022-08-19 10:17 UTC, merged